View all tags
googleinterns/cabby pull request #108
Opened 2021-11-09 11:18 UTC by tzufgoogle

The web application is SPA.

We added:
1. Added all tags to view on the map.
2. Added 2 main pivots (a total of 3 main pivots).
3. The pivots near the goal do not show the name tag.
4. Added data v4 with these changes.

2021-11-16 14:18 UTC, jasonbaldridge requested changes
Thanks! Quite a large PR. Couldn't review in very fine detail, but found a number of things to fix and/or consider.

2021-11-16 14:18 UTC, jasonbaldridge commented on cabby/geo/visualization/database.py
> +from flask import *
Don't import all from a module. Instead 'import flask' and then use flax.foo, etc., or use 'from flax import foo' for each thing you need.

2021-11-16 14:18 UTC, jasonbaldridge commented on cabby/geo/visualization/forms.py
> +#     raise ValidationError('Try again to describe the goal.')
Can delete commented out code.

2021-11-16 14:18 UTC, jasonbaldridge commented on cabby/geo/visualization/templates/follower_task.html
> +	L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
Is this a private access token that shouldn't be checked into to OS code? (If so, need to regenerate and pass in another way.)

2021-11-16 14:18 UTC, jasonbaldridge commented on cabby/geo/walk.py
> +   "beyond_pivot", "around_goal_pivot_1", "around_goal_pivot_2", "around_goal_pivot_3"]
This was defined in util.py -- why have it in two spots?

2022-01-16 07:28 UTC, tzufgoogle reviewed
1. Changed NOT_DISPLAY_TAGS name 
2. Removed SECRET_KEY

2022-01-19 13:43 UTC, jasonbaldridge approved these changes
Thanks!

2022-01-20 14:27 UTC, merged