Geomodel
googleinterns/cabby pull request #40
Opened 2020-09-30 09:19 UTC by tzufgoogle

"""Simple text classification example.
This script trains a text classifier on a dataset containing paragraphs that
are linked to s2cells. 

A sentence is encoded with an BERT and a binary prediction is made from CLS 
token embedding using an MLP.

Example command line call:
$ bazel-bin/cabby/model/text/s2cellid_prediction/model_trainer \
  --data_dir ~/data/wikigeo/pittsburgh  \
  --dataset_dir ~/model/wikigeo/dataset/pittsburgh \
  --region Pittsburgh \ 
  --s2_level 12 \
  --output_dir ~/tmp/output\

"""

2020-09-30 18:33 UTC, sayalikulkarni requested changes
One high level input - there seem to be too many models in the same PR. Suggest that you split them next time into one PR per model so it is easier to review :) 
It would also help to refactor out certain common code like the training loops, eval metrics etc. if any.

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/geo/util.py
> +  return (coord[0], coord[1])
I know that this is tricky - but some libraries use latitude-longitude versus some specify longitude,latitude. Is there a way to unify this? e.g L396 versus L411 are confusing unless we see that one uses shapely.Point
Consider using a named tuple

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/geo/util.py
> +  Args:
'Arguments' to be consistent?

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/geo/util.py
> +  Args:
same here

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/geo/util.py
> +    s2cell_ids: Sequence[int]) -> Sequence[Tuple]:
int64?

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/geo/util.py
> +  line_point_2 = np.array(line_segment.coords[len(line_segment.coords)-1])
why -1? what is the unit considered?

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/geo/util.py
> +  return 1 if line_segment.distance(projected_point) < 1e-8 else 0
can rewrite this as:
return (line_segment.distance(projected_point) < 1e-8)

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/geo/util.py
> +    1 if the projected point is in the segment and 0 if inot.
change the return to a bool instead of 0-1

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/model/text/region_prediction/model_trainer.py
> +    'cuda') if torch.cuda.is_available() else torch.device('cpu')
did you train on cpu?!

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/model/text/region_prediction/model_trainer.py
> +    eval_every=len(train_dataset) // 10
prefer to eval every _static_ number of steps so even if the training set gets really large, we see the intermediate eval epochs.
eval_every=100 or 50?

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/model/text/region_prediction/train.py
> +          topi = topi.squeeze().detach().cpu().numpy()
does this work on a gpu?

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/model/text/region_prediction/train.py
> +          attention_mask = batch['attention_mask'].to(device)
do you need a epsilon to avoid NaN when computing the logits with the attention mask?

2020-09-30 18:33 UTC, sayalikulkarni commented on cabby/model/text/s2cellid_prediction/BUILD
> +
too many empty lines

2020-10-01 08:45 UTC, tzufgoogle commented
Build, run and tests working.

2020-10-08 01:48 UTC, sayalikulkarni approved these changes
this looks good to go...

2020-10-08 16:13 UTC, merged