Wikigeo full page
googleinterns/cabby pull request #42
Opened 2020-10-01 06:09 UTC by tzufgoogle

Wikigeo data where instead of taking the 3 sentences in a page as one sample takes all sentences and creates a sample per sentence

2020-10-02 17:01 UTC, sayalikulkarni requested changes
initial inputs - based on Pittsburgh data. 
also related to the data - 
$ wc -l /mnt/hackney/data/cabby/wikigeo/wikigeo_pittsburgh_raw_7.json
23209 /mnt/hackney/data/cabby/wikigeo/wikigeo_pittsburgh_raw_7.json

$ wc -l  /mnt/hackney/data/cabby/wikigeo/v11/pittsburgh_*.json
   1991 /mnt/hackney/data/cabby/wikigeo/v11/pittsburgh_dev.json
   1991 /mnt/hackney/data/cabby/wikigeo/v11/pittsburgh_test.json
  15926 /mnt/hackney/data/cabby/wikigeo/v11/pittsburgh_train.json
  19908 total

v11 should have much more examples than the older ones like v7 - no? Whats missing?

2020-10-03 04:38 UTC, tzufgoogle reviewed
Build, test run working

2020-10-03 04:38 UTC, tzufgoogle commented on cabby/data/extract_test.py
> +sys.path.append("/home/tzuf_google_com/dev/cabby")
removed

2020-10-03 04:38 UTC, tzufgoogle commented on cabby/data/wikipedia/query.py
> +  text = text.split('== See also ==')[0]
Added External links removal

2020-10-03 07:48 UTC, tzufgoogle commented
The comparison sould be to - /mnt/hackney/data/cabby/wikigeo/wikigeo_pittsburgh_raw_9.json
(this version doesn't have duplicate text).  This version has 18,258  wherase the current v11 version has 19,908.

2020-10-03 12:35 UTC, tzufgoogle commented
Fixed now there are 33216 for Pittsburgh

2020-10-08 19:12 UTC, sayalikulkarni approved these changes
good to go...

2020-10-08 20:01 UTC, merged