Wikigeo with osm samples
googleinterns/cabby pull request #44
Opened 2020-10-01 14:31 UTC by tzufgoogle

Extended the WikiGeo dataset by adding:
(1) samples based on Wikidata info only
(2) samples based on OSM info only.

Build, run tests working.

2020-10-05 18:53 UTC, sayalikulkarni requested changes
This too seems like a very large PR :) 
it is easier to test, review and submit smaller code pieces rather than one large PR. May be try to split more next time?

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +  '''Get data from Wikipedia based on Wikidata items"
no double quotes here.

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +  # # Get Wikipedia titles.
may be left from some auto-formatting, but why "# #"? just "#" :)

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +  for list_backlinks, original_wikipedia, original_wikidata in \
may be just call this backlinks?

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +      wikigeo_sample = wikigeo.WikigeoEntity.from_wiki_items(
this is actually the full text right? why sample?

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +  '''Get data from Wikipedia and Wikidata by region"
replace with .
and everywhere below.

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +  '''Get data from Wikipedia and Wikidata by region and add sampes created from
typo?

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +def get_data_by_region_expansive(region: Text, path_osm: Text) -> Sequence:
what does expansive mean?
looking at the code it seems like it is returning the region given the specific region boundaries. may be rename the function as get_data_by_region_boundaries?

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract.py
> +  poi = poi[poi['s2cellids'].str.len() <= 10]  # Remove large entities.
may be define a constant for this?
Also lets count these examples. Are there too many? may be affected by how the OSM entities are named. or rather how certain type of wiki entities are named.

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract_wikigeo_contexts_expansive.py
> +$ bazel-bin/cabby/data/extract_wikigeo_contexts_expansive \
same suggestion about the name as above.

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/extract_wikigeo_contexts_expansive.py
> +FLAGS = flags.FLAGS
duplicate

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/osm_item.py
> +    # drop_col = ['element_type', 'wheelchair', 'internet_access',
remove commented code?

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/osm_item.py
> +  return text.isascii()
does this drop names like:
https://en.wikipedia.org/wiki/Angoul%C3%AAme

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/osm_item.py
> +        text += connect + v
you can do:
k_text = []
v_text = []

if  ... : 
  k_text.append(k)
else:
  v_text.append(v)

and then at the end - 
" and ".join(v_text, k_text)

confirm that this works ok for the sequence you need before updating.

2020-10-05 18:53 UTC, sayalikulkarni commented on cabby/data/wikidata/info_item.py
> +  sample: Text = attr.ib(init=False)
relates to one of the comments above. the attribute can be named tags instead of sample?

2020-10-06 13:37 UTC, tzufgoogle reviewed
I didn't change the function name - it expands over another function with the addition of 2 new types of samples.
resolved conflicts.
build, run, test working.

2020-10-08 01:43 UTC, sayalikulkarni requested changes
There still seem to be some pending changes? Is there a pending commit to be pushed?

2020-10-08 01:43 UTC, sayalikulkarni commented on cabby/data/extract.py
> +  '''Get data from Wikipedia and Wikidata by region"
Are the changes merged? Seems like I still see it as a "

2020-10-08 01:43 UTC, sayalikulkarni commented on cabby/data/extract.py
> +def get_data_by_region_expansive(region: Text, path_osm: Text) -> Sequence:
may be rename as get_data_by_region_with_osm?
'expansive' is not very evident

2020-10-08 01:43 UTC, sayalikulkarni commented on cabby/data/extract.py
> -    ref_qid"
pending fix?

2020-10-08 01:43 UTC, sayalikulkarni commented on cabby/data/extract_wikigeo_contexts_expansive.py
> +FLAGS = flags.FLAGS
still pending?

2020-10-09 06:01 UTC, tzufgoogle reviewed
Changed file name

2020-10-13 09:12 UTC, merged