Add initial KG building functions.
googleinterns/cabby pull request #47
Opened 2020-10-03 02:22 UTC by jpalowitch

2020-10-07 10:27 UTC, tzufgoogle requested changes
Just a few things: 
(1) typing wrong (leads to a build error)
(2) a function without typing
(3) maybe add a test for get_geofenced_wikidata_relations?

2020-10-07 18:02 UTC, jpalowitch commented on cabby/data/wikidata/query.py
> +def get_filter_string(place_filter: [Sequence[Text]],
Fixed by 54ba279

2020-10-07 18:03 UTC, jpalowitch commented on cabby/data/wikidata/query.py
> +                         place_filter: [Sequence[Text]] = []):
Fixed by 54ba279

2020-10-07 18:03 UTC, jpalowitch commented on cabby/data/wikidata/query.py
> +                                     place_filter: [Sequence[Text]] = [],
Fixed by 54ba279

2020-10-07 18:03 UTC, jpalowitch commented on cabby/data/metagraph/utils.py
> +                                   edge_attribute_columns):
Fixed by 54ba279

2020-10-07 18:03 UTC, jpalowitch commented on cabby/data/metagraph/utils.py
> +def convert_pandas_df_to_metagraph(df, source_column, target_column,
Fixed by 54ba279

2020-10-09 05:26 UTC, tzufgoogle approved these changes
Let's merge this

2020-10-13 09:48 UTC, tzufgoogle requested changes
The re are some building errors and test errors. 
Run:
(1) source build_all.sh
(2) source test_all.sh

2020-10-13 09:48 UTC, tzufgoogle commented on cabby/data/wikidata/query.py
> +def get_filter_string(place_filter: [Sequence[Text]],
Change: [Sequence[Text]] => Sequence[Text]

2020-10-13 09:48 UTC, tzufgoogle commented on cabby/data/wikidata/query_test.py
> +    qid_set = set(list(wd_relations.place))
wd_relations doesn't have place

2020-10-13 18:08 UTC, jpalowitch commented on cabby/data/wikidata/query.py
> +def get_filter_string(place_filter: [Sequence[Text]],
Fixed by 49c50b2

2020-10-13 18:20 UTC, jpalowitch commented on cabby/data/wikidata/query_test.py
> +    qid_set = set(list(wd_relations.place))
Fixed by 49d6a81

2020-10-13 19:45 UTC, tzufgoogle approved these changes
LGTM

2020-10-13 20:19 UTC, merged