Dualencoder
googleinterns/cabby pull request #55
Opened 2020-10-12 17:32 UTC by tzufgoogle

This is a dual-encoder(two-tower) architecture that encodes both instructions and S2Cells in 
the same dense vector space. This allows us to embed new S2Cells and instructions.
The dual-encoder has a network structure for representing both S2Cells and instructions and then a and a cosine function to compute similarity between representations. 
The text encoder includes a DistilBert with uncased pretrained weights for embedding of the sentence. Then the CLS token embedding goes through a feed-forward layer, a RELU activation function and another feed-forward layer to reduce the dim to X.
The cellid is a binary vector that goes through one feed-forward layer, such that the dimension changes to X, the same as the text representation dimension. We train with three cellids: The correct cellid, a neighbor cellid, and a far cellid (more than 2 KM). We sum the losses over the three cellids and backpropagate.

2020-10-13 20:02 UTC, jasonbaldridge requested changes
Great to have the dual encoder implementation! I have a bunch of bigger and smaller requests. Please go ahead and resolve the conversations for the trivial stuff when you've addressed them.

I'm still confused as to why your editor isn't sorting out the formatting stuff correctly. I'd appreciate it if you could look into it and make it work. That would save both of us time and mental effort in future.

2020-10-13 20:02 UTC, jasonbaldridge commented on cabby/model/text/util.py
> +  '''Funcion for saving model.'''
also, several times below

2020-10-13 20:02 UTC, jasonbaldridge commented on cabby/model/text/util.py
> +              label_to_cellid: Dict[int, int]) -> Sequence[Tuple[float, float]]:
Fix indentation.

2020-10-14 15:28 UTC, tzufgoogle reviewed
Made the requested changes including adding TextGeoDataset

2020-10-14 15:28 UTC, tzufgoogle commented on cabby/model/text/util.py
> +def binary_representation(array_int, dim):
Added both doc and test

2020-10-14 15:28 UTC, tzufgoogle commented on cabby/model/text/util.py
> +          valid_loss: float):
fixed

2020-10-14 15:28 UTC, tzufgoogle commented on cabby/model/text/util.py
> +  '''Funcion for saving model.'''
Fixed all

2020-10-14 15:28 UTC, tzufgoogle commented on cabby/model/text/util.py
> +          device: torch.device) -> Dict[Text, Sequence]:
fixed.

2020-10-14 15:28 UTC, tzufgoogle commented on cabby/model/text/util.py
> +              label_to_cellid: Dict[int, int]) -> Sequence[Tuple[float, float]]:
Fixed.

2020-10-14 18:05 UTC, jasonbaldridge approved these changes
Thanks! LGTM. ( But you might still need to push a missing commit?)

2020-10-14 18:05 UTC, jasonbaldridge commented on cabby/model/text/dual_encoder/dataset.py
> +  def __getitem__(self, idx: int):
Thanks!

2020-10-14 18:05 UTC, jasonbaldridge commented on cabby/model/text/dual_encoder/model_trainer.py
> +  if os.path.exists(dataset_path):
Great! Minor nit: seems like we don't need named args for loading and saving, but no problem if you want to keep it as is.

2020-10-14 18:05 UTC, jasonbaldridge commented on cabby/model/text/dual_encoder/train.py
> +    cellids, neighbor_cells, far_cells = cellids.float().to(device), neighbor_cells.float().to(device), far_cells.float().to(device)
Doesn't seem changed. Did you forget to push the commit?

2020-10-14 18:41 UTC, merged

2020-10-15 16:12 UTC, sayalikulkarni commented
Great to see this out! Thanks Jason for covering up the review.