Fixed poi addition to graph
googleinterns/cabby pull request #57
Opened 2020-10-15 07:47 UTC by tzufgoogle

Fixed poi addition to graph such that it will allow addition of poi beyond graph such as might be the  case in poi from wikidata.

2020-10-19 11:05 UTC, jasonbaldridge requested changes
The description of the PR is very cryptic. Please write that more clearly and give an example.

A few comments/suggestions in the review to handle, and then this will be all set.

2020-10-19 11:05 UTC, jasonbaldridge commented on cabby/geo/walk.py
> +MAX_NUM_FAILED = 10
max num what failed? (make sure the name indicates this)

2020-10-19 11:05 UTC, jasonbaldridge commented on cabby/geo/walk.py
> +      # Find nodes whithin 2000 meter path distance.
sp: whithin -> within

2020-10-19 11:05 UTC, jasonbaldridge commented on cabby/geo/walk.py
> +      logging.info("Created sample {}/{}".format(counter,n_samples))
It's generally shorter and easier to read when using f'' instead, e.g.:

```
logging.info(f"Created sample {counter}/{n_samples}".)
```

Can you switch to this style here and in future?

2020-10-20 07:25 UTC, tzufgoogle reviewed
1. Changed comments.
2. Added functions for calculating new osmid.
3. Changes string format style.

2020-10-20 11:11 UTC, jasonbaldridge approved these changes
LGTM: I'd design some of this differently, but let's get this checked in so you can keep moving.

2020-10-20 11:11 UTC, jasonbaldridge commented on cabby/geo/map_processing/map_structure.py
> +    # If the POI is already in the graph, do not add it.
First, the naming of the function and the semantics are weird. The function is called add_single_poi_to_graph(), which doesn't imply you are going to get any edges back, nor that if the POI exists that nothing happens.

Second, if you are returning a list, then the empty list is a perfect return value when nothing happens. It's hard to reason about null or missing values. You have a narrow use case for handling them, but others may use this same function in a year and not have that context. (

That said, let's move on and I'll consider refactoring it later!

2020-10-20 17:15 UTC, merged